package UI.KhuVucHocTap;

import BLL.ThongTinSuDungBLL;
import BLL.thietbiBLL;
import DAL.ThongTinSuDung.ThongTinSuDungDAL;
import DAL.ThongTinSuDung.thongtinsd;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class nhapMaTBForm extends javax.swing.JFrame {

    /**
     * Creates new form nhapMaTBForm
     */
    int type, matv;
    ThongTinSuDungBLL ttsdbll = new ThongTinSuDungBLL();
    
    public nhapMaTBForm() {
        initComponents();
    }
    
    public nhapMaTBForm(int t, int id) {
        initComponents();
        type = t;
        matv = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaTB = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập mã thiết bị muốn mượn/trả");

        btnSubmit.setText("Xác nhận");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(txtMaTB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtMaTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String maTB = txtMaTB.getText();
        int matb;
        try {
            matb = Integer.parseInt(maTB);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập số cho mã thiết bị");
            return;
        }
        if (type == 1) {
            thietbiBLL tbBLL = new thietbiBLL();
            
            if (!tbBLL.isMaTbExisted(matb)) {
                JOptionPane.showMessageDialog(this, "Mã thiết bị này không tồn tại!");
                return;
            }
            
            if (ttsdbll.isThietBiDangDcMuon(matb)) {
                JOptionPane.showMessageDialog(this, "Thiết bị này đang được mượn, vui lòng nhập mã thiết bị khác");
                return; 
            }
            
            LocalDateTime time = LocalDateTime.now();
            int matt = ttsdbll.getmaxMaTT();
            thongtinsd ttsd = new thongtinsd(matt, matv, matb, null, time, null);
            boolean result = ttsdbll.addThongTinSdTB(ttsd);
            if(result) {
                JOptionPane.showMessageDialog(this, "Bạn đã mượn thiết bị thành công");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Mượn thiết bị thất bại");
            }
        } else {
            thongtinsd ttsd = ttsdbll.getThongTinSdDangMuon(matv, matb);
            if (ttsd == null) {
                JOptionPane.showMessageDialog(this, "Bạn không mượn thiết bị này!");
                return;
            }
            
            LocalDateTime time = LocalDateTime.now();
            ttsd.setTGTra(time);
            boolean result = ttsdbll.updateThongTinSd(ttsd);
            if (result) {
                JOptionPane.showMessageDialog(this, "Bạn đã trả thiết bị thành công!");
                this.dispose();
            } 
            else {
                JOptionPane.showMessageDialog(this, "Trả thiết bị thất bại!");
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nhapMaTBForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nhapMaTBForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nhapMaTBForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nhapMaTBForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nhapMaTBForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMaTB;
    // End of variables declaration//GEN-END:variables
}
