/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.XuLy;

import BLL.ThanhVienBLL;
import BLL.XuLyBLL;
import DAL.XuLy.xuly;
import java.awt.Point;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dat dep trai
 */
public class xulyPanel extends javax.swing.JPanel {

    private XuLyBLL xlBLL = new XuLyBLL();
    private ThanhVienBLL tvBLL = new ThanhVienBLL();
    DefaultTableModel model = new DefaultTableModel();
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    public xulyPanel() {
        initComponents();
        loadXuLy();
        cbHinhthucxl.addItem("Khóa thẻ 1 tháng");
        cbHinhthucxl.addItem("Khóa thẻ 2 tháng");
        cbHinhthucxl.addItem("Bồi thường");
        cbHinhthucxl.addItem("Khóa thẻ 1 tháng và bồi thường");
        
        
        cbTrangthaixl.addItem("0");
        cbTrangthaixl.addItem("1");
        
        List<String> matvList = tvBLL.getAllMaTV();
        for (String MaTV : matvList) {
            cbMatv.addItem(MaTV);
        }
        
//        List<String> maxlList = xlBLL.loadcbMaxl();
//        for (String MaXl : maxlList) {
//            cbMaxl.addItem(MaXl);
//        }
        
    }
    
    public void loadXuLy() {
        model = (DefaultTableModel) jbXuLy.getModel();
        model.setRowCount(0);
        List<xuly> xulyList = xlBLL.loadXuLy();
        for (xuly xl : xulyList) {
            Object[] row = {xl.getMaXL(), xl.getMaTV(), xl.getHinhThucXL(), xl.getSoTien() , xl.getNgayXL(), xl.getTrangThaiXL()};
            model.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jbXuLy = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbMatv = new javax.swing.JComboBox<>();
        cbHinhthucxl = new javax.swing.JComboBox<>();
        txtSotien = new javax.swing.JTextField();
        cbTrangthaixl = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbSearch = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(950, 513));

        jbXuLy.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jbXuLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaXL", "MaTV", "HinhThucXL", "SoTien", "NgayXL", "TrangThai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jbXuLy.setRowHeight(30);
        jbXuLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbXuLyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jbXuLy);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("XỬ LÝ VI PHẠM");

        cbMatv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMatv.setSelectedItem(1120010007);
        cbMatv.setToolTipText("");
        cbMatv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatvActionPerformed(evt);
            }
        });

        cbHinhthucxl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbHinhthucxl.setSelectedItem("Khóa thẻ 1 tháng");
        cbHinhthucxl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHinhthucxlActionPerformed(evt);
            }
        });

        txtSotien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotienActionPerformed(evt);
            }
        });

        cbTrangthaixl.setSelectedItem(0);
        cbTrangthaixl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrangthaixlActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("MaTV");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("HinhThucXL");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("SoTien");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("TrangThaiXL");
        jLabel6.setToolTipText("");

        btnDelete.setBackground(new java.awt.Color(204, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnEditFocusLost(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(204, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MaXL", "MaTV" }));
        cbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(cbMatv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbHinhthucxl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 44, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTrangthaixl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMatv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbHinhthucxl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTrangthaixl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMatvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMatvActionPerformed

    private void cbHinhthucxlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHinhthucxlActionPerformed
        if(cbHinhthucxl.getSelectedItem().equals("Bồi thường") || cbHinhthucxl.getSelectedItem().equals("Khóa thẻ 1 tháng và bồi thường")){
            txtSotien.setEditable(true);
        }else{
            txtSotien.setEditable(false);
            txtSotien.setText("");
        }
    }//GEN-LAST:event_cbHinhthucxlActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String selectedMaXL = String.valueOf(jbXuLy.getValueAt(jbXuLy.getSelectedRow(), 0));
        int MaTV = Integer.parseInt(selectedMaXL);
        if(xlBLL.xoaXuly(MaTV) == true){
//            cbMaxl.removeItem(selectedMaXL);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadXuLy();
        }else{
            JOptionPane.showMessageDialog(this, "Xóa thất bại! Hãy thử lại");
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = jbXuLy.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 vi phạm để chỉnh sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String selectMaXL = String.valueOf(jbXuLy.getValueAt(jbXuLy.getSelectedRow(), 0));
            int MaXl = Integer.parseInt(selectMaXL);
            xuly xuly;
            xuly =  xlBLL.getXulybyMaxl(MaXl);
                    updateXuly detail = new updateXuly(this, xuly);
                    detail.setLocationRelativeTo(null);
                    detail.setVisible(true); 
            loadXuLy();
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        loadXuLy();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int MaXL = xlBLL.getmaxMaXL();
        String selectedMaTV = (String) cbMatv.getSelectedItem();
        int MaTV = Integer.parseInt(selectedMaTV);
    
        String HinhthucXL = (String) cbHinhthucxl.getSelectedItem();
        Integer Sotien = txtSotien.getText().isEmpty() ? null : Integer.valueOf(txtSotien.getText());
        
        String Trangthaistring = (String) cbTrangthaixl.getSelectedItem();
        int Trangthai = Integer.parseInt(Trangthaistring);
        // Lấy ngày giờ hiện tại
        Date currentDate = new Date();

        // Định dạng ngày giờ thành chuỗi
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = dateFormat.format(currentDate);

        xuly newXuly = new xuly(MaXL, MaTV ,HinhthucXL , Sotien, formattedDateTime, Trangthai);
        if ( xlBLL.themXuLy(newXuly) == true){
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }else{
            JOptionPane.showMessageDialog(this, "Thêm không thành công. Thành viên này chưa xử lí vi phạm cũ");
        }
        
        loadXuLy();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(cbSearch.getSelectedItem() == "MaXL"){
            model.setRowCount(0); 
            try {
                List<xuly> xulyList = xlBLL.getXulyBySimilarMaxl(txtSearch.getText());
                for(xuly xuly : xulyList) {
                    Object[] row = {xuly.getMaXL(), xuly.getMaTV(), xuly.getHinhThucXL(), xuly.getSoTien() , xuly.getNgayXL(), xuly.getTrangThaiXL()};
                    model.addRow(row);
                }
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Vui lòng nhập số nguyên.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                  }
        }else{
            model.setRowCount(0); 
            try {
                List<xuly> xulyList = xlBLL.getXulyBySimilarMatv(txtSearch.getText());
                for(xuly xuly : xulyList) {
                    Object[] row = {xuly.getMaXL(), xuly.getMaTV(), xuly.getHinhThucXL(), xuly.getSoTien() , xuly.getNgayXL(), xuly.getTrangThaiXL()};
                    model.addRow(row);
                }
            } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Vui lòng nhập số nguyên.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbTrangthaixlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrangthaixlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrangthaixlActionPerformed

    private void txtSotienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotienActionPerformed
        
    }//GEN-LAST:event_txtSotienActionPerformed

    private void jbXuLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbXuLyMouseClicked
        String selectMaXL = String.valueOf(jbXuLy.getValueAt(jbXuLy.getSelectedRow(), 0));
        int MaXl = Integer.parseInt(selectMaXL);
        Point point = evt.getPoint();
        xuly xulydetail;
        int row = jbXuLy.rowAtPoint(point);
                if(evt.getClickCount() == 2 && row != -1 ){
                    xulydetail =  xlBLL.getXulybyMaxl(MaXl);
                    xulyDetail detail = new xulyDetail(this, xulydetail);
                    detail.setLocationRelativeTo(null);
                    detail.setVisible(true); 
                }
    }//GEN-LAST:event_jbXuLyMouseClicked

    private void btnEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditFocusLost
       
    }//GEN-LAST:event_btnEditFocusLost

    private void cbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbHinhthucxl;
    private javax.swing.JComboBox<String> cbMatv;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JComboBox<String> cbTrangthaixl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbXuLy;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSotien;
    // End of variables declaration//GEN-END:variables
}
